[project]
name = "darus-review-mcp"
version = "0.1.1"
description = "DaRUS Review MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp==3.4.4",
    "pydataverse[mcp]",
    "python-dotenv>=1.2.1",
]

[tool.uv.sources]
pydataverse = { git = "https://github.com/haeussma/pyDataverse.git", branch = "dev" }
